### PR TITLE
Simpler "wiring" of log messages to web client.

### PR DESCRIPTION
**Pull request by tmontes**
General idea:
* Having a custom log bridge firing log events to be handled by the websocket server is too complex when the the logging system supports dynamic addition/removal of "log observers".

Changes:
* Throw the log bridge away.
* Update the websocket server protocol:
  * Implements the "log observer" interface via the `__call__` method.
  * Adds itself as a log observer once the connection is established.
  * Removes itself as a log observer when disconnected.

This required:
* Updating the log manager with `add_observer` / `remove_observer` methods.

Along the way:
* Simplified its general log implementation: less duplication.
* Web server factory no longer needs to cooperate in pushing logs to clients: less code.
* Main code became even simpler.

### CODE REVIEW

**Comment by nununo** [comment]
coool! makes sense. much simpler!

**Comment by tmontes** [comment]
...agreed, it all *lighted up in my head* while improving the event management APIs: just had to be done for *beauty*'s sake!

**Comment by tmontes** [comment]
By the way:
* Maybe, we can improve the web socket protocol/factory "wiring" to "arduino raw data pushes" following a similar approach.

Idea:
* Have the protocol tell "subscribe to those calls" on connect and "unsubscribe" on disconnect.
* This is, probably, simpler, and removes lots of code from the factory and the protocol it self: as it no longer will be necessary to "track" the connected protocol at the factory level.

**Comment by tmontes** [comment]
Went ahead with the idea in #55: simpler and less code is easier to understand, manage and, of course, *more beautiful*.

**Pull request merged**
