### PR TITLE
Chart enhancements: dual readings + threshold annotations.

### LINKED ISSUE #27: Plot arduino input level thresholds along with actual readings.

### PR DESCRIPTION
**Pull request by tmontes**
Several, not so complex changes, towards #27. On the first commit:
* Arduino sensor input now pushes two named values to the `raw_data_callable`: the raw reading and the aggregated derivative (agd).
* Websocket server, as a `raw_data_callable`, now pushes all named values it gets to the connected web client.
* The web client chart now plots two chart datasets, raw and agd, using independent y-axes for each.

On the second commit, towards #27:
* Found the [chartjs annotation plugin](https://github.com/chartjs/chartjs-plugin-annotation) which is exactly what we need.
* After fiddling a bit on the web client, reached something that works.
* The web client now handles `chart-threshold` typed messages and updates the threshold annotations.

Pending:
* Server side will need to push `chart-threshold` messages on start.

So this *does not* close #27, yet.

### CODE REVIEW

**Comment by tmontes** [comment]
Note:
* While at it, updated web client to read new threshold levels, working towards #28.
* That is what the latest commit, 77dd48fcb04a72cc68b538a9b0cc9e7c7960c3f2, is about.

**Comment by nununo** [comment]
Tiago, when you said:

"So this does not close #27, yet."

you automatically closed #27 lol

**Comment by tmontes** [comment]
> Tiago, when you said:
> "So this does not close #27, yet."
> you automatically closed #27 lol

...these are the motives *I love* these sorts of (pseudo?) fancy tool cleverness. \*sigh!\* ;-)

**Comment by nununo** [comment]
https://www.theverge.com/2017/1/7/14200210/amazon-alexa-tech-news-anchor-order-dollhouse

**Comment by tmontes** [comment]
> https://www.theverge.com/2017/1/7/14200210/amazon-alexa-tech-news-anchor-order-dollhouse

What's not to love about modern day incredible-but-still-pretty-dumb human interaction AI implementations?

IOW: *What could possibly go wrong?* ;-)

**Pull request merged**
