### PR TITLE
Systemd .service template file in place.

### PR DESCRIPTION
**Pull request by tmontes**
Partial #33 solution.

Notes:
* Sharing progress.
* Please do not merge yet.

Next:
* Update `README.md`, including instructions on how to set this up.

### CODE REVIEW

**Comment by tmontes** [comment]
**IMPORTANT NOTE**

The current `.service` file fails to successfully (and cleanly) stop unless the *better* `dbus-run-session` is used. See #32.

**Comment by nununo** [comment]
Tiago, let me know when I can marge this PR!

**Comment by tmontes** [comment]
@nununo, ready for merging.

Spent (invested!) quite a bit of time ensuring clean, synchronised stopping (not really needed, I know) regardless of "good" or "bad" `dbus-run-session`. :)

**Comment by tmontes** [comment]
@nununo, I merged it myself: see? :)

**Pull request merged**
